### ISSUE TITLE
Error when using as unauthenticated user

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/switchtheme#2]
Well, it most cases it's unlikely that unauthenticated users would have access to this. This module was requested for the Ready2Wear initiative and it might make sense for that project. 

I just tested the module and it worked fine for an authenticated admin. However, when I made it possible for an unauthenticated user to switch themes, the act of switching themes generated this error.

> EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'name' in EntityDatabaseStorageController->save() (line 676 of /var/www/triplo/ready2wear/simplo/src/core/modules/entity/entity.controller.inc).

AND

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'name': INSERT INTO {users} (uid, name, pass, mail, signature, signature_format, created, access, login, status, timezone, language, picture, init, data) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12, :db_insert_placeholder_13, :db_insert_placeholder_14); Array ( [:db_insert_placeholder_0] => 17 [:db_insert_placeholder_1] => [:db_insert_placeholder_2] => $S$EFXECXzvciECfwX7gcmcWaedxo3nvRfXDlIJ6PTLkkNoc/0lozPx [:db_insert_placeholder_3] => [:db_insert_placeholder_4] => [:db_insert_placeholder_5] => [:db_insert_placeholder_6] => 0 [:db_insert_placeholder_7] => 0 [:db_insert_placeholder_8] => 0 [:db_insert_placeholder_9] => 0 [:db_insert_placeholder_10] => America/Chicago [:db_insert_placeholder_11] => [:db_insert_placeholder_12] => 0 [:db_insert_placeholder_13] => [:db_insert_placeholder_14] => a:1:{s:5:"theme";s:5:"tatsu";} ) in backdrop_write_record() (line 8139 of /var/www/triplo/ready2wear/simplo/src/core/includes/common.inc).

![Simplo__](https://user-images.githubusercontent.com/3144571/95637974-d6ad1800-0a58-11eb-9dd0-f02deb8b31ff.png)

NOTE: This error is happening on a site with lots of other modules and themes. I'll try testing on a fresh install to rule out conflicts.

**Comment by stpaultim** [comment]
I tested this on a clean install. The only thing I did was add this module and enable the Bartik theme.

I was able to use the module as a site editor, but when I tried using it as an unauthenticated user, I got the same errors.

**Comment by hosef** [comment]
@stpaultim Thanks for testing this. I found the place where this was happening. Essentially it was trying to save the user when the user was anonymous, so it was failing. I have changed it to correctly save it in the session when an actual user account is not available.

**Comment by stpaultim** [comment]
@hosef - confirmed that this fixed the problem on my site.
